### ISSUE TITLE
Both Symfony exception and Tracy are visible (Symfony exception should not be rendered)

### ISSUE THREAD

**Issue by mhujer** [VasekPurchart/Tracy-Blue-Screen-Bundle#5]
The Bundle can be installed into the Symfony 3 app, but does not work perfectly. It renders the exception with Tracy but the Symfony exception in rendered below as well.

**Comment by VasekPurchart** [comment]
I know about this issue and I have spent a lot of time trying to solve it, but to no avail. This bundle relies on overriding the default Twig error template and rendering Tracy as the "standard" output. 

From my testing this is not a SF 3 issue (as I thought originally as well), but older. I have not tested every version, but from my random tries 2.6.13 was still working, but 2.8.8 was not. The issue is long standing and current state best described here: https://github.com/symfony/symfony/issues/6919#issuecomment-238591390. 

I have not found any other reliable way to overload the template and other option would be a custom controller, which has the disadvantage, that it could alter the default behavior, which is not inteded (and would me much more difficult to maintain).

If you find anything useful, please let me know.

PS: changing the title to better suit the problem.

**Comment by mhujer** [comment]
I just checked the Symfony versions and:
- version 2.7.21 is fine
- version 2.8.0 is broken

After that I did `git bisect` between them and this is the commit that broke it: https://github.com/symfony/symfony/commit/ff3c107f14cfc4ff4f4e2186e2ac88de83ea34f9
(part of https://github.com/symfony/symfony/pull/15970)

**Comment by mhujer** [comment]
There is a PR https://github.com/symfony/symfony/pull/19586 that fixes the issue in Symfony

**Comment by mhujer** [comment]
It was fixed in Symfony 3.2.2
